import { media } from './media'

/** A cropped image: `ratio` is the Figma frame's width / height, applied with object-fit: cover. */
export type MediaItem = { src: string; ratio: number; radius?: number; href?: string; alt?: string; bg?: string; fit?: 'contain' }

export type RichText = string | { before: string; label: string; href: string; after?: string }

/**
 * Detail-page content blocks, listed in the same order as the Figma frame.
 * - heading: JG Heading (40px top gap, rule, 56px text)
 * - paragraphs: 28px body copy in the 1200px column, paragraphs 28px apart
 * - note: 44px remark in the column (e.g. "/The Following Images are all generated by AI.")
 * - video: 16:9 YouTube embed in the column
 * - media: one row of cropped images (one item = full width, two = pair), 28px gap
 * - columns: side-by-side stacks of cropped images; `widths` are fractions of the column, `justify`
 *   centers the group when it is narrower than the column (JingDong composite)
 */
export type Block =
  | { kind: 'heading'; text: string }
  | { kind: 'paragraphs'; text: RichText[] }
  | { kind: 'note'; text: string }
  | { kind: 'video'; id: string; title: string }
  /** Generic iframe embed (e.g. LinkedIn post); `ratio` is the Figma box width / height. */
  | { kind: 'embed'; src: string; title: string; ratio: number }
  | { kind: 'media'; items: MediaItem[]; topGap?: number }
  | { kind: 'columns'; columns: MediaItem[][]; widths?: number[]; gap?: number; rowGap?: number; justify?: 'center' }

export type Project = {
  slug: string
  path: string
  title: string
  cardTitle: string
  cardType: string
  cardSector: string
  cardDate: string
  /** Card default image; `cardHover` is shown on hover and falls back to `cover` (the detail page cover). */
  cardImage: string
  cardHover?: string
  cover: string
  symbol: string
  intro: string
  introLink?: { label: string; href: string }
  /** Optional link on the cover title (COVID19 links to the live dashboard). */
  titleHref?: string
  /** Cover crop; Figma uses contain for Eureka, cover elsewhere. */
  coverFit?: 'contain'
  specifications: readonly [string, string][]
  blocks: Block[]
}

/** Card images supplied by the user on 2026-09-19 (replacing the Figma teasers they flagged as wrong). */
const cards = '/assets/cards'

const ratio = (width: number, height: number) => width / height
/** Full-width image in the 1200px column, cropped to the given Figma height. */
const full = (src: string, height: number, extra: Partial<MediaItem> = {}): MediaItem => ({ src, ratio: ratio(1200, height), ...extra })
/** One of two side-by-side images (586px each at 1512, 28px gap), cropped to the given height. */
const half = (src: string, height: number, extra: Partial<MediaItem> = {}): MediaItem => ({ src, ratio: ratio(586, height), ...extra })

export const projects: Project[] = [
  {
    slug: 'noe', path: '/work/noe', title: 'Noë & Associates', cardTitle: 'Noë & Associates',
    cardType: 'Design Agency, Marketing Film, AIGC', cardSector: 'Real Estate, Hospitality', cardDate: 'Summer / 2026',
    cardImage: `${cards}/noe-default.webp`, cardHover: `${cards}/noe-hover.webp`, cover: media.noe.imgPlaceHolder, symbol: media.noe.imgProperty1Aigc,
    intro: 'During my internship at Noë & Associates, I worked at the intersection of design, AI, and creative production, leveraging these tools to produce marketing films for the real estate sector.',
    specifications: [
      ['Type', 'Creative Technologist Intern, Design Agency, Marketing Film, AIGC'],
      ['Tools', 'ComfyUI, NanoBanana Pro, KlingAI, Seedance, Claude, Adobe Creative'],
      ['Location', 'Soho, Manhattan, NewYork, US'],
      ['Date', 'Summer / 2026'],
    ],
    blocks: [
      { kind: 'heading', text: 'AI Film' },
      { kind: 'paragraphs', text: ['The following is a collection of samples that are not related to any client projects I participated in. They are only used to demonstrate the aesthetic I produced.'] },
      // Figma annotation: temporary YouTube 3k7AbJDKz3k, to be replaced by the user later.
      { kind: 'video', id: '3k7AbJDKz3k', title: 'Noë & Associates AI film' },
      // Figma 159:1647 + 159:1650 (annotation: LinkedIn embed, 1200×620 box).
      { kind: 'paragraphs', text: ['One more Client’s LinkedIn post that shows our work!'] },
      { kind: 'embed', src: 'https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7505162738852147200?compact=1', title: 'Client LinkedIn post featuring Noë & Associates work', ratio: ratio(1200, 620) },
      { kind: 'paragraphs', text: ['I contributed to many projects, including:', 'Masterise Homes (The Ritz-Carlton Residences, Hanoi) | Rosewood Hotel & Residences, Raleigh | 101 Franklin NYC | Ethancia Resort | Le Rocher'] },
      { kind: 'paragraphs', text: ['My work involved translating architectural renders, photography, and creative direction into polished AI-generated shots while maintaining consistency in composition, materiality, lighting, brand identity, and the Noë aesthetic.'] },
      { kind: 'note', text: '/The Following Images are all generated by AI.' },
      { kind: 'media', items: [full(media.noe.imgRectangle15, 510)] },
      { kind: 'media', items: [full(media.noe.imgRectangle16, 675)] },
      { kind: 'media', items: [full(media.noe.imgRectangle17, 1000)] },
      { kind: 'media', items: [full(media.noe.imgRectangle18, 490)] },
      { kind: 'media', items: [full(media.noe.imgRectangle19, 490)] },
      { kind: 'media', items: [half(media.noe.imgRectangle20, 432), half(media.noe.imgRectangle21, 432)] },
      { kind: 'media', items: [half(media.noe.imgRectangle22, 446), half(media.noe.imgRectangle23, 446)] },
      { kind: 'media', items: [full(media.noe.imgRectangle24, 670)] },
      { kind: 'media', items: [full(media.noe.imgRectangle25, 670)] },
      { kind: 'media', items: [full(media.noe.imgRectangle26, 670)] },
      { kind: 'media', items: [full(media.noe.imgRectangle27, 670)] },
      { kind: 'heading', text: 'AI Pipeline Development' },
      { kind: 'paragraphs', text: ['I also collaborated with my colleague Henry to build an internal AI generation pipeline. The core purpose of the pipeline was to improve the efficiency of generating AI shots at scale, while reducing the time wasted on frequent asset and file transfers during collaboration. The entire system was hosted on a Mac Mini, with all generated assets backed up locally. Through Tailscale, everyone could easily access the system from anywhere, enabling seamless collaboration across multiple people.'] },
      { kind: 'media', items: [full(media.noe.imgRectangle11, 600)] },
      { kind: 'media', items: [full(media.noe.imgRectangle13, 599)] },
      { kind: 'media', items: [full(media.noe.imgRectangle14, 528)] },
      { kind: 'media', items: [{ src: media.noe.img202609181635021, ratio: ratio(1909, 1273) }, { src: media.noe.img202609181635201, ratio: ratio(1828, 1206) }] },
      { kind: 'paragraphs', text: ['The features of the pipeline included:', 'Project management | Integration of multiple AI models | Asset management (scenes, reference images, and prompts) | Automatic shot-list importing | AI shot selection | Multi-user collaboration'] },
      { kind: 'heading', text: 'AI model R&D' },
      { kind: 'paragraphs', text: ['Another major part of my role focused on researching and documenting cutting-edge AI models, looking for any opportunity to improve our existing workflows.The areas I researched included Kling AI API, Nano Banana API, Comfy MCP, LTX models, Seedance 2.5, AI chips, SAM/SAM2, Netflix VOID Model, etc.Rather than treating generative AI as a standalone tool, I viewed these technologies as individual modules for building my own tools, and explored different possibilities for combining them together.'] },
      { kind: 'heading', text: 'My Takeaway' },
      { kind: 'paragraphs', text: ['AIGC once again demonstrated its extraordinary pace of evolution and its growing commercial potential. My experience at Noë made me realize that when AI is built on top of established client relationships, mature production workflows, and real business needs, its value can scale far beyond the technology itself.', 'As the technology continues to evolve, I believe its commercial impact will be amplified by the systems, relationships, and creative practices built around it.'] },
    ],
  },
  {
    slug: 'cue', path: '/work/cue', title: 'CUE Group', cardTitle: 'CUE',
    cardType: 'Tech Company, Consumer Product, AIGC', cardSector: 'Internet Service', cardDate: 'Summer / 2025',
    cardImage: `${cards}/cue-default.webp`, cover: media.cue.imgPlaceHolder, symbol: media.cue.imgProperty1Aigc,
    intro: 'During my internship at CUE Group, I focused on building and refining ComfyUI workflows that powered the core features of its consumer-facing AI products. CUE is a large Chinese technology group with extensive experience in digital business services.',
    specifications: [
      ['Type', 'Product Manager Intern, Consumer Product, AIGC'],
      ['Tools', 'ComfyUI, Adobe Creative'],
      ['Location', 'WangJing, Beijing, China'],
      ['Date', 'Summer / 2025'],
    ],
    blocks: [
      { kind: 'heading', text: 'Consumer Product' },
      { kind: 'paragraphs', text: ['The core consumer product was an interactive kiosk that captures a user’s face and transforms them into recognizable IP characters while preserving their key facial features and identity.', 'My work focused on developing and iterating the underlying ComfyUI workflow to improve the consistency, usability, and output quality of the experience.'] },
      // Figma 100:1663: the two kiosk shots sit inside 978:1459 / 586:875 frames, contained (first on white).
      { kind: 'media', topGap: 14, items: [{ src: media.cue.imgGroup231, ratio: ratio(978, 1459), fit: 'contain', bg: '#fff' }, { src: media.cue.imgGroup241, ratio: ratio(586, 875), fit: 'contain' }] },
      { kind: 'media', topGap: 14, items: [{ src: media.cue.imgGroup232, ratio: ratio(389, 299) }, { src: media.cue.imgGroup242, ratio: ratio(586, 451) }] },
      { kind: 'heading', text: 'B2B Solutions' },
      { kind: 'paragraphs', text: ['Building on the same facial transformation workflow, I developed additional applications for commercial use cases, including automated ID photo generation, multi-person face swapping, and customized AI workflows for B2B marketing projects. I designed a marketing concept for Transsion.lnc focused on personalized, face-based poster generation, allowing users to see themselves reflected more directly in the lifestyle and values the brand wanted to communicate.', 'The project followed an end-to-end workflow: creative planning → custom LoRA training → ComfyUI workflow development → product launch.'] },
      { kind: 'media', topGap: 14, items: [media.cue.imgBeatCrafter, media.cue.imgBlockBuilder, media.cue.imgCityMagician, media.cue.imgFashionTrendsetter].map((src) => ({ src, ratio: 1 })) },
      { kind: 'media', topGap: 14, items: [media.cue.imgHashtagHustler, media.cue.imgNightlifePro, media.cue.imgSocialDynamo, media.cue.imgWastelandArtist].map((src) => ({ src, ratio: 1 })) },
      { kind: 'heading', text: 'Takeaway' },
      { kind: 'paragraphs', text: ['CUE was my first opportunity to work directly on AIGC applications designed for consumer use. It gave me a clearer understanding of both the commercial potential of consumer-facing generative AI and the difficulty of creating outputs that users are genuinely willing to pay for.', 'I also learned how valuable ComfyUI can be in an early-stage product environment. Its flexibility made it possible to quickly test, adjust, and iterate on product features as requirements evolved.'] },
    ],
  },
  {
    slug: 'jingdong', path: '/work/jingdong', title: 'JingDong', cardTitle: 'JingDong',
    cardType: 'Tech Company, BoB Solutions, AIGC', cardSector: 'Retail Industry', cardDate: 'Summer / 2024',
    cardImage: `${cards}/jingdong-default.webp`, cover: media.jingdong.imgPlaceHolder, symbol: media.jingdong.imgProperty1Aigc,
    intro: 'During my internship at JD.com, I worked on a B2B service product that used AI to help third-party merchants on the JD platform efficiently generate product marketing images and develop marketing strategies. My work spanned model development, merchant workflows, product experience, and large-scale commercial applications.',
    specifications: [
      ['Type', 'Creative Technologist Intern, Tech Company, BoB Solutions, UX Design, AIGC'],
      ['Tools', 'Stable Diffusion, Figma, Adobe Creative'],
      ['Location', 'YiZhuang, Beijing, China'],
      ['Date', 'Summer / 2024'],
    ],
    blocks: [
      { kind: 'heading', text: 'JingDiandian — AI Tools for E-commerce Sellers' },
      { kind: 'paragraphs', text: ['JD.com is one of China’s leading e-commerce platforms. Our target users were third-party merchants on the platform who needed product marketing support but lacked dedicated marketing and design teams.', 'JingDiandian is an AI-powered content generation tool designed for third-party merchants on JD.com.'] },
      { kind: 'media', items: [full(media.jingdong.imgRectangle12, 597)] },
      { kind: 'paragraphs', text: ['I trained more than 20 LoRA and SDXL models for different product photography scenarios and developed reusable AI image templates for merchant use. I also optimized existing high-usage templates through prompt engineering and parameter tuning, contributing to a 65% increase in monthly usage for selected templates.'] },
      // Figma 103:1617: phone screenshot + two stacks of three squares, centred in the column.
      {
        kind: 'columns', justify: 'center', gap: 28, rowGap: 14, widths: [343.9 / 1200, 202.3 / 1200, 202.3 / 1200],
        columns: [
          [{ src: media.jingdong.imgImage1, ratio: ratio(343.9, 634.9) }],
          [{ src: media.jingdong.img2, ratio: 1, radius: 4, bg: '#fff' }, { src: media.jingdong.img, ratio: 1, radius: 4, bg: '#fff' }, { src: media.jingdong.img3, ratio: 1, radius: 4, bg: '#fff' }],
          [{ src: media.jingdong.imgImage120, ratio: 1, radius: 16 }, { src: media.jingdong.imgImage30, ratio: 1, radius: 16 }, { src: media.jingdong.imgImage15, ratio: 1, radius: 4, bg: '#fff' }],
        ],
      },
      { kind: 'paragraphs', text: ['Beyond model training, I worked on improving the merchant workflow around AI generation. This included simplifying interaction steps, reducing unnecessary design operations, and making the generation process more accessible to users without professional design or AI experience.', 'I also contributed to the product interface, graphic templates, and campaign visuals, allowing me to work across the full experience from model output to the final merchant-facing product.'] },
      { kind: 'heading', text: 'AI Fashion Styling' },
      { kind: 'paragraphs', text: ['I also contributed to JD Fashion’s AI styling feature, which generates complete outfit recommendations for users.', 'My work focused on defining the visual direction and clothing style taxonomy for different user profiles. I designed more than 30 AI outfit templates and corresponding background environments, which were later integrated into the JD App.'] },
      { kind: 'paragraphs', text: ['This project gave me experience working with generative AI in a large-scale consumer platform, where visual quality also needed to align with recommendation logic, user expectations, and the broader shopping experience.'] },
      { kind: 'heading', text: 'Takeaway' },
      { kind: 'paragraphs', text: ['My experience at JD.com was my first exposure to how AIGC could create real value in a commercial context. Even though the technology was still at a relatively early stage at the time, with Stable Diffusion 1.5 and SDXL as the dominant models, the flexibility of LoRA models combined with clearly defined business needs was already enough to unlock meaningful commercial value.', 'JD.com also showed me the importance of the AI pipeline itself. AI models provide the underlying technology, but what ultimately turns that technology into a useful product is the engineering layer around it — the workflows, tools, and platforms that make AI reliable, scalable, and usable in real-world scenarios.'] },
    ],
  },
  {
    slug: 'covid19', path: '/work/covid19', title: 'COVID19 Dashboard', cardTitle: 'Covid 19 Dashboard', titleHref: 'https://mr-speakless.github.io/ITP-dataVisualize-dashboard/',
    cardType: 'Non-Profit Project, Web Dashboard', cardSector: 'In Collaboration with NYU Faculty', cardDate: 'Mar / 2026',
    cardImage: `${cards}/covid19-default.webp`, cover: media.covid19.imgPlaceHolder, symbol: media.covid19.imgSkillVi,
    intro: 'I worked with John Henry Thompson and Shindy Johnson to redesign the dashboard for their COVID-19 Impact project.',
    introLink: { label: 'COVID-19 Impact project', href: 'https://itp.nyu.edu/covid19impactproject/' },
    specifications: [
      ['Type', 'NYU Course Project, Web Development, UI Design'],
      ['Tools', 'Figma, Codex'],
      ['Location', 'Tisch, NYU, New York, US'],
      ['Date', 'Mar / 2026'],
    ],
    blocks: [
      { kind: 'paragraphs', text: ['COVID-19 Impact is a website that continuously tracks the development of the pandemic and the broader social issues revealed through it. I visualized COVID-19 data in a way that highlights forms of inequality that are often overlooked in aggregated statistics, particularly spatial inequality and temporal inequality.', { before: 'The website was developed using React and deployed through my ', label: 'GitHub repo', href: 'https://github.com/Mr-speakless/ITP-dataVisualize-dashboard', after: '.' }] },
      // Figma annotation: the three dashboard images link to the live dashboard.
      { kind: 'media', items: [{ src: media.covid19.img186ShotsSo1, ratio: ratio(1440, 1018), href: 'https://mr-speakless.github.io/ITP-dataVisualize-dashboard/', alt: 'COVID-19 dashboard, view 1' }] },
      { kind: 'media', items: [{ src: media.covid19.img186ShotsSo2, ratio: ratio(1440, 1018), href: 'https://mr-speakless.github.io/ITP-dataVisualize-dashboard/', alt: 'COVID-19 dashboard, view 2' }] },
      { kind: 'media', items: [{ src: media.covid19.img186ShotsSo3, ratio: ratio(1200, 703), href: 'https://mr-speakless.github.io/ITP-dataVisualize-dashboard/', alt: 'COVID-19 dashboard, view 3' }] },
    ],
  },
  {
    slug: 'eureka', path: '/work/eureka', title: 'Eureka', cardTitle: 'Eureka', coverFit: 'contain',
    cardType: 'AI Film', cardSector: 'Satirical Animated Short', cardDate: 'Dec / 2024',
    cardImage: `${cards}/eureka-default.webp`, cardHover: `${cards}/eureka-hover.webp`, cover: media.eureka.imgPlaceHolder, symbol: media.eureka.imgProperty1Aigc,
    intro: 'Eureka is an AI-animated short film that I co-created with two friends during my undergraduate studies.The film follows three scientists who, after an unexpected accident, mistakenly believe they have discovered an extraterrestrial civilization. Their discovery quickly leads to disagreement and escalating tension, only for them to eventually realize that the entire event was a misunderstanding.',
    specifications: [
      ['Type', 'Personal Project, AI Film, VFX, AIGC'],
      ['Tools', 'ComfyUI, Green Screen Shooting'],
      ['Location', 'Beijing, China'],
      ['Date', 'Dec / 2024'],
    ],
    blocks: [
      { kind: 'paragraphs', text: ['Using the “discovery of alien civilization” as a metaphor, Eureka explores the anxiety created by result-oriented thinking and the obsession with achieving success too quickly. The film touches on themes including impatience, self-deception, goals versus process, appearance versus reality, perceptual distortion, and illusion.', 'AI-generated imagery was not only used as a production tool, but also became part of the visual language of the film, creating a contrast between reality and fiction, discovery and imagination.'] },
      { kind: 'video', id: '_Y6XSFS4PVM', title: 'Eureka short film' },
      { kind: 'heading', text: 'Production Process' },
      { kind: 'paragraphs', text: ['The film was created through a workflow combining green-screen filming with AI-based stylized rendering in post-production.', 'During pre-production and filming, we used a large green screen and live-action performances. This allowed us to maintain greater control over character movement, facial expressions, and other performance details.'] },
      { kind: 'media', items: [full(media.eureka.imgRectangle13, 674)] },
      { kind: 'media', items: [full(media.eureka.imgRectangle18, 674)] },
      { kind: 'media', items: [full(media.eureka.imgRectangle19, 674)] },
      { kind: 'media', items: [full(media.eureka.imgRectangle20, 674)] },
      { kind: 'media', items: [full(media.eureka.imgRectangle21, 674)] },
      { kind: 'paragraphs', text: ['We also built virtual environments in Blender to support larger-scale animated scenes.'] },
      { kind: 'media', items: [full(media.eureka.imgRectangle22, 691)] },
      { kind: 'media', items: [full(media.eureka.imgRectangle14, 691)] },
      { kind: 'paragraphs', text: ['The live-action footage was then edited into the final sequence before AI processing.'] },
      { kind: 'paragraphs', text: ['Finally, we used ComfyUI for stylized rendering, style transfer, compositing, and final image synthesis.'] },
      { kind: 'media', items: [full(media.eureka.imgRectangle16, 829)] },
      // Figma 139:8726: raw frames (left) beside their AI-rendered counterparts (right), 580px columns.
      {
        kind: 'columns', gap: 40, rowGap: 28,
        columns: [
          [{ src: media.eureka.imgRectangle13, ratio: ratio(580, 378.13) }, ...[media.eureka.imgR21, media.eureka.imgR31, media.eureka.imgR41, media.eureka.imgR51, media.eureka.imgR61, media.eureka.imgR111, media.eureka.imgR81, media.eureka.imgR91, media.eureka.imgR101, media.eureka.imgR71, media.eureka.imgR121].map((src) => ({ src, ratio: ratio(580, 333.55) }))],
          [{ src: media.eureka.img187, ratio: ratio(580, 378.13) }, ...[media.eureka.imgD21, media.eureka.imgD31, media.eureka.imgD41, media.eureka.imgD51, media.eureka.imgD61, media.eureka.imgD71, media.eureka.imgD81, media.eureka.imgD91, media.eureka.imgD101, media.eureka.imgD111, media.eureka.imgD121].map((src) => ({ src, ratio: ratio(580, 333.55) }))],
        ],
      },
      { kind: 'heading', text: 'Acknowledgements' },
      { kind: 'media', items: [full(media.eureka.imgRectangle17, 718)] },
      { kind: 'paragraphs', text: ['Special thanks to all the friends who helped us throughout the production, as well as the support and resources provided by our school. We could not have completed this project without them.'] },
    ],
  },
  {
    slug: 'cape', path: '/work/cape', title: 'CAPE', cardTitle: 'CAPE',
    cardType: 'Product Design, Wearable product, Prototyping', cardSector: 'Industrial Design', cardDate: 'Nov / 2024',
    cardImage: `${cards}/cape-default.webp`, cover: media.capecover.imgPlaceHolder, symbol: media.work.imgSkillVi2,
    intro: '"CAPE" is a smart gadget that identifies and helps people improve their sitting posture. To ascertain the condition of the shoulder and neck, CAPE tracks three main sites of the shoulder and neck. It tells the user, via a pop-up software, to keep good posture.',
    specifications: [
      ['Type', 'Industrial design'],
      ['Tools', 'Blender'],
      ['Location', 'Beijing, China'],
      ['Date', 'Nov / 2024'],
    ],
    // Rendered by pages/CapeStory.tsx.
    blocks: [],
  },
  {
    slug: 'eros-trilogy', path: '/work/eros-trilogy', title: 'Eros Trilogy', cardTitle: 'ErosTrilogy',
    cardType: 'Art Installation', cardSector: 'Fine Art', cardDate: 'Apr / 2024',
    cardImage: `${cards}/eros-default.webp`, cardHover: `${cards}/eros-hover.webp`, cover: media.eros.imgPlaceHolder, symbol: media.eros.imgSkillVi,
    intro: 'I use myoelectric sensors to sense the activity of the human mouth and control a giant airbag that represents re-pressed Eros, switching back and forth between tense and soothing states. This led to the production of an experimental video and a short interactive narrative.',
    specifications: [
      ['Type', 'New Media Art, interactive Installation, experimental film'],
      ['Tools', 'Arduino, sensors, servo, projection'],
      ['Location', 'Beijing, China'],
      ['Date', 'Apr / 2024'],
    ],
    // Rendered by pages/ErosStory.tsx (Figma 80:8779 is a bespoke layout).
    blocks: [],
  },
]

export const projectByPath = new Map(projects.map((project) => [project.path, project]))
